FROM python:3.10.1 AS base

# Run basic container update
RUN apt-get update -q -y

# Install Oracle Client
WORKDIR /opt/oracle
RUN apt-get update && apt-get install -y unixodbc-dev libaio1 wget unzip iputils-ping \
    && wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip \
    && unzip instantclient-basiclite-linuxx64.zip \
    && rm -f instantclient-basiclite-linuxx64.zip \
    && cd /opt/oracle/instantclient* \
    && rm -f *jdbc* *occi* *mysql* *README *jar uidrvci genezi adrci \
    && echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf \
    && ldconfig

# Install core packages
RUN mkdir -p /opt/dagster/dagster_home /opt/dagster/app
RUN pip install dagit dagster-postgres dagster-docker

# Copy your code and workspace to /opt/dagster/app
COPY repo.py workspace.yaml requirements.txt /opt/dagster/app/
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
WORKDIR /opt/dagster/app
RUN pip install -r requirements.txt

# Copy dagster instance YAML to $DAGSTER_HOME
COPY dagster.yaml /opt/dagster/dagster_home/
WORKDIR /opt/dagster/app


FROM base AS build
EXPOSE 3000
ENTRYPOINT ["dagit", "-h", "0.0.0.0", "-p", "3000"]