FROM apache/airflow:latest

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    vim build-essential unixodbc-dev libaio1 wget unzip iputils-ping \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
USER airflow
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
# RUN pip install --no-cache-dir apache-airflow-providers-odbc
RUN mkdir code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


