version: '3'
services:
  postgres:
    container_name: postgresql
    hostname: postgresql
    image: postgres:latest
    volumes:
      - 'postgresql_master_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_DB=${DATABASE_DEFAULT:-postgres}
    networks:
      - services
    ports:
      - 5432:5432
    restart: always

volumes:
  postgresql_master_data:
    driver: local

networks:
  services:
    name: ${DATABASE_NETWORK:-postgres.network}
